spring:
  application:
    name: ec-site

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/ec_site
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true # TLSによる暗号化