name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
